failed load Hlxcfg.txt
tried dir = c:\Users\User\source\repos\JeanMandoo\Hlxcfg.txt
current wk_dir = C:\Users\User\AppData\Local\Programs\Python\Python311\python.exe
failed load Hlxcfg.txt
tried dir = c:\Users\User\source\repos\JeanMandoo\modules\modules\utagger\Hlxcfg.txt
current wk_dir = C:\Users\User\AppData\Local\Programs\Python\Python311\python.exe
can not make customDic : ../udic4_3/customDic.txt
can not make customDic : ../udic4_3/customDic.txt
can not make customDic : ../udic4_3/customDic.txt
can not make customDic : ../udic4_3/customDic.txt
can not make customDic : ../udic4_3/customDic.txt
can not make customDic : ../udic4_3/customDic.txt
can not make customDic : ../udic4_3/customDic.txt
can not make customDic : ../udic4_3/customDic.txt
can not make customDic : ../udic4_3/customDic.txt
can not make customDic : ../udic4_3/customDic.txt
